### ISSUE TITLE
Quiestion: how to efficiently and fast transfer a docker image from the host to the Jetson?

### ISSUE THREAD

**Issue by ikhann** [dusty-nv/jetson-containers#218] opened 2023-01-26 14:23 UTC
Hi!

I am faced with the issue of a need for free disk space when transferring the Docker image to Jetson. 
I got the error "no space left on device" when running the command "docker load <image>":

![image](https://user-images.githubusercontent.com/21182465/214859007-176eb063-bb4d-4195-964d-4f48d0f8a0ce.png)

But at the same time, I see that Jetson has more space than required for the docker image.

I will be very pleased if you help solve it and advise how to efficiently and fast transfer a docker image with a high degree of compression and load it afterward.

I really appreciate any help you can provide.

**Comment by dusty-nv** [comment] 2023-01-26 15:14
@ikhann I think the issue is that the docker image first needs to be transferred similar to an archive (like .tar.gz or similar), then decompressed, so the process can actually take up more disk space that just the image itself.   I'm not sure how to change this behavior with Docker, although perhaps some way exists.   Is it possible for you to mount additional storage?

**Comment by ikhann** [comment] 2023-01-26 15:55
> @ikhann I think the issue is that the docker image first needs to be transferred similar to an archive (like .tar.gz or similar), then decompressed, so the process can actually take up more disk space that just the image itself. I'm not sure how to change this behavior with Docker, although perhaps some way exists. Is it possible for you to mount additional storage?

Hi!
[This](https://forums.developer.nvidia.com/t/moving-docker-directory-to-nvme-ssd-cloudnative-demo-on-jetson/185248) helped me solve the problem, but only partially.

But now it really looks like I don't have enough space to load the docker image.

Result of the df -h command before transferring 25GB docker image:
![image](https://user-images.githubusercontent.com/21182465/214883104-8a661ad1-f6dd-4578-8d0c-0893cc7f3938.png)



Result of the df -h command before the no space error:
![image](https://user-images.githubusercontent.com/21182465/214883182-130566b3-ccf9-4fd6-ab7e-15eaac80b5ad.png)

I use a 64 GB Sd card,  so I guess I should increase the amount of space with a 128 GB sd card or an external nvme card.

Thank you!

**Closed** 2023-01-28 00:33 UTC
